#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#My Settings
bspc config window_gap 3

bspc config focus_follows_pointer true

sxhkd -c ~/.config/sxhkd/sxhkdrc &

xsetroot -cursor_name left_ptr &

feh --bg-fill ~/Pictures/Wallpapers/house-in-nature.jpg

polybar &

dunst &
